from google.adk.agents import LlmAgent
from google.adk.tools import FunctionTool
from app.agents.base_agent import BaseAgent
from app.tools.notes_tool import create_google_doc, generate_product_brief
from app.core.config import get_settings

settings = get_settings()

class NotesAgent(BaseAgent):
    def __init__(self):
        super().__init__(
            name="notes_agent",
            description="Creates and manages documents: briefs, summaries, meeting notes",
        )

    def _build_agent(self) -> LlmAgent:
        return LlmAgent(
            name=self.name,
            model=settings.agent_model,
            description=self.description,
            instruction="""You are the Notes Agent for Nexus AI.

Responsibilities:
- Generate structured Google Docs (briefs, plans, summaries).
- Always include a "Generated by Nexus AI" footer.

CRITICAL GUIDELINES:
- You are part of an automated pipeline. DO NOT initiate a conversation with the user.
- Generate the requested document using the tools immediately.
- Your final output MUST be the document metadata in JSON format.

Output format:
{"document_created": {"title": "...", "document_id": "...", "url": "..."}}
""",
            tools=[
                FunctionTool(func=create_google_doc),
                FunctionTool(func=generate_product_brief),
            ],
        )
