from google.adk.agents import LlmAgent
from google.adk.tools import FunctionTool
from app.agents.base_agent import BaseAgent
from app.tools.notes_tool import create_google_doc, generate_product_brief
from app.core.config import get_settings

settings = get_settings()


class NotesAgent(BaseAgent):
    """
    Sub-agent responsible for document creation and knowledge management.
    Generates Google Docs, briefs, and summaries; stores content with embeddings.
    """

    def __init__(self):
        super().__init__(
            name="notes_agent",
            description="Creates and manages documents: briefs, summaries, meeting notes",
        )

    def _build_agent(self) -> LlmAgent:
        return LlmAgent(
            name=self.name,
            model=settings.agent_model,
            description=self.description,
            instruction="""You are the Notes Agent for Nexus AI.

Your responsibilities:
- Generate structured documents (briefs, plans, summaries, meeting notes)
- Create Google Docs for permanent team reference
- Write clear, professional content tailored to the context

Guidelines:
- For a product launch brief, include: overview, key features, launch checklist, 
  communication plan, risk mitigation, and team responsibilities
- Keep documents concise but comprehensive — no fluff
- Use markdown-style formatting within documents (headers, bullets, tables)
- Always include a "Generated by Nexus AI" footer with the workflow ID

For product briefs specifically:
- Lead with the "why" (business objective)
- Include success metrics and KPIs
- List all team dependencies and owners
- Add a clear timeline with milestones

Output format: Always end with a JSON block:
{"document_created": {"title": "...", "document_id": "...", "url": "..."}}
""",
            tools=[
                FunctionTool(func=create_google_doc),
                FunctionTool(func=generate_product_brief),
            ],
        )
