from typing import Optional, Dict, Any, List
from googleapiclient.discovery import build
from google.oauth2.credentials import Credentials
from google.oauth2 import service_account
import os
from app.core.config import get_settings
from app.core.logging import get_logger

logger = get_logger(__name__)
settings = get_settings()

SCOPES = [
    "https://www.googleapis.com/auth/documents",
    "https://www.googleapis.com/auth/drive.file",
]


def _get_docs_service():
    """Build Google Docs service using saved OAuth credentials."""
    if settings.google_service_account_path and os.path.exists(settings.google_service_account_path):
        creds = service_account.Credentials.from_service_account_file(
            settings.google_service_account_path,
            scopes=SCOPES,
        )
        return build("docs", "v1", credentials=creds)

    token_path = "credentials/google_token.json"
    if not os.path.exists(token_path):
        raise RuntimeError("Google credentials not found. Run OAuth flow first.")
    creds = Credentials.from_authorized_user_file(token_path, SCOPES)
    return build("docs", "v1", credentials=creds)


def _get_drive_service():
    if settings.google_service_account_path and os.path.exists(settings.google_service_account_path):
        creds = service_account.Credentials.from_service_account_file(
            settings.google_service_account_path,
            scopes=SCOPES,
        )
        return build("drive", "v3", credentials=creds)

    token_path = "credentials/google_token.json"
    if not os.path.exists(token_path):
        raise RuntimeError("Google credentials not found.")
    creds = Credentials.from_authorized_user_file(token_path, SCOPES)
    return build("drive", "v3", credentials=creds)


async def create_google_doc(
    title: str,
    content: str,
    folder_id: Optional[str] = None,
) -> Dict[str, Any]:
    try:
        docs_service = _get_docs_service()

        doc = docs_service.documents().create(body={"title": title}).execute()
        doc_id = doc["documentId"]

        requests = [
            {
                "insertText": {
                    "location": {"index": 1},
                    "text": content,
                }
            }
        ]
        docs_service.documents().batchUpdate(
            documentId=doc_id, body={"requests": requests}
        ).execute()

        if folder_id:
            drive_service = _get_drive_service()
            drive_service.files().update(
                fileId=doc_id,
                addParents=folder_id,
                removeParents="root",
                fields="id, parents",
            ).execute()

        doc_url = f"https://docs.google.com/document/d/{doc_id}/edit"
        logger.info("google_doc_created", doc_id=doc_id, title=title)

        return {
            "success": True,
            "document_id": doc_id,
            "url": doc_url,
            "title": title,
        }
    except Exception as e:
        logger.error("google_doc_creation_failed", error=str(e))
        return {"success": False, "error": str(e)}


async def generate_product_brief(
    product_name: str,
    launch_date: str,
    key_features: List[str],
    target_audience: str,
    team_channel: Optional[str] = None,
) -> Dict[str, Any]:
    features_text = "\n".join(f"• {f}" for f in key_features) if key_features else "• To be confirmed"
    channel_note = f"\nTeam channel: {team_channel}" if team_channel else ""

    content = f"""PRODUCT LAUNCH BRIEF
{'='*50}

Product: {product_name}
Launch Date: {launch_date}
Target Audience: {target_audience}{channel_note}

KEY FEATURES
{'─'*30}
{features_text}

LAUNCH CHECKLIST
{'─'*30}
• Marketing materials finalized
• Engineering sign-off complete
• Customer support briefed
• Press kit prepared
• Analytics tracking configured
• Rollback plan documented

COMMUNICATION PLAN
{'─'*30}
• Internal announcement: 48 hours before launch
• Press release: Launch day
• Customer email: Launch day
• Social media posts: Scheduled

RISKS AND MITIGATIONS
{'─'*30}
• Risk: Server load spike — Mitigation: Auto-scaling configured
• Risk: Critical bug found — Mitigation: Rollback procedure ready
• Risk: Low adoption — Mitigation: Beta user feedback incorporated

Generated by Nexus AI System
"""

    return await create_google_doc(
        title=f"Product Launch Brief — {product_name} ({launch_date})",
        content=content,
    )


async def generate_product_brief_from_request(
    user_request: str,
    product_name: Optional[str] = None,
    launch_date: Optional[str] = None,
    target_audience: Optional[str] = None,
    key_features: Optional[List[str]] = None,
    team_channel: Optional[str] = None,
) -> Dict[str, Any]:
    inferred_product_name = product_name or "Product Launch"
    inferred_launch_date = launch_date or "TBD"
    inferred_target_audience = target_audience or "Internal team and target customers"
    inferred_key_features = key_features or [
        "Launch scope definition",
        "Readiness review",
        "Cross-functional coordination",
        "Customer communication",
    ]

    content = f"""PRODUCT LAUNCH BRIEF
{'='*50}

Request: {user_request}

Product: {inferred_product_name}
Launch Date: {inferred_launch_date}
Target Audience: {inferred_target_audience}
{"Team channel: " + team_channel if team_channel else ""}

KEY FEATURES / FOCUS AREAS
{'─'*30}
""" + "\n".join(f"• {f}" for f in inferred_key_features) + """

EXECUTION PLAN
{'─'*30}
• Finalize launch scope and success criteria
• Confirm engineering and operational readiness
• Prepare marketing and communication assets
• Align support and internal stakeholders
• Monitor launch-day execution and risks

RISKS AND MITIGATIONS
{'─'*30}
• Risk: Readiness gaps — Mitigation: Pre-launch checklist review
• Risk: Communication issues — Mitigation: Single owner and channel
• Risk: Customer confusion — Mitigation: Clear launch messaging

Generated by Nexus AI System
"""

    return await create_google_doc(
        title=f"Product Launch Brief — {inferred_product_name}",
        content=content,
    )
